name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  find:
    name: Find add-ons
    runs-on: ubuntu-latest
    outputs:
      addons: ${{ steps.addons.outputs.addons_list }}
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: 🔍 Find add-on directories
        id: addons
        uses: home-assistant/actions/helpers/find-addons@master

      - name: 🛠 Ensure add-ons output is valid
        run: |
          if [[ -z "${{ steps.addons.outputs.addons_list }}" || "${{ steps.addons.outputs.addons_list }}" == "[]" ]]; then
            echo "No add-ons found. Exiting workflow."
            exit 1
          fi

  lint:
    name: Lint add-on ${{ matrix.path }}
    runs-on: ubuntu-latest
    needs: find
    if: needs.find.outputs.addons != '[]'  # Only run if add-ons exist
    strategy:
      matrix:
        path: ${{ fromJson(needs.find.outputs.addons) }}
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v4

      - name: Test output
        run: ls -la ${{ matrix.path }}

      - name: Set env
        run: echo "INPUT_PATH=${{ matrix.path }}" >> $GITHUB_ENV

      - name: 🚀 Run Home Assistant Add-on Lint
        uses: frenck/action-addon-linter@v2
        with:
          path: "./${{ matrix.path }}"
          community: true